name: les_mehdi_font_du_ski
description: Les Mehdi Font Du Ski
version: 0.0.1
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
  flame_audio: ^1.3.5
  async: ^2.10.0
  drift: ^2.4.2
  intl: ^0.18.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  build_runner: ^2.1.10
  drift_dev: ^2.4.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: AldotheApache
      fonts:
        - asset: assets/font/AldotheApache.ttf